/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VatRegisterRouteImport } from './routes/vat-register'
import { Route as ReceiptPaymentRouteImport } from './routes/receipt-payment'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LedgersRouteImport } from './routes/ledgers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptPaymentIndexRouteImport } from './routes/receipt-payment.index'
import { Route as ChallansIndexRouteImport } from './routes/challans.index'
import { Route as BillsIndexRouteImport } from './routes/bills.index'
import { Route as MastersVendorsRouteImport } from './routes/masters.vendors'
import { Route as MastersItemsRouteImport } from './routes/masters.items'
import { Route as MastersFixedAssetsRouteImport } from './routes/masters.fixed-assets'
import { Route as MastersCustomersRouteImport } from './routes/masters.customers'
import { Route as MastersCompaniesRouteImport } from './routes/masters.companies'
import { Route as ChallansNewRouteImport } from './routes/challans.new'
import { Route as ChallansIdRouteImport } from './routes/challans.$id'
import { Route as BillsNewRouteImport } from './routes/bills.new'
import { Route as BillsIdRouteImport } from './routes/bills.$id'
import { Route as ReceiptPaymentPaymentVoucherNewRouteImport } from './routes/receipt-payment.payment-voucher.new'
import { Route as ReceiptPaymentPaymentVoucherIdRouteImport } from './routes/receipt-payment.payment-voucher.$id'

const VatRegisterRoute = VatRegisterRouteImport.update({
  id: '/vat-register',
  path: '/vat-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptPaymentRoute = ReceiptPaymentRouteImport.update({
  id: '/receipt-payment',
  path: '/receipt-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgersRoute = LedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptPaymentIndexRoute = ReceiptPaymentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceiptPaymentRoute,
} as any)
const ChallansIndexRoute = ChallansIndexRouteImport.update({
  id: '/challans/',
  path: '/challans/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersVendorsRoute = MastersVendorsRouteImport.update({
  id: '/masters/vendors',
  path: '/masters/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersItemsRoute = MastersItemsRouteImport.update({
  id: '/masters/items',
  path: '/masters/items',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersFixedAssetsRoute = MastersFixedAssetsRouteImport.update({
  id: '/masters/fixed-assets',
  path: '/masters/fixed-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCustomersRoute = MastersCustomersRouteImport.update({
  id: '/masters/customers',
  path: '/masters/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCompaniesRoute = MastersCompaniesRouteImport.update({
  id: '/masters/companies',
  path: '/masters/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallansNewRoute = ChallansNewRouteImport.update({
  id: '/challans/new',
  path: '/challans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallansIdRoute = ChallansIdRouteImport.update({
  id: '/challans/$id',
  path: '/challans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsNewRoute = BillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptPaymentPaymentVoucherNewRoute =
  ReceiptPaymentPaymentVoucherNewRouteImport.update({
    id: '/payment-voucher/new',
    path: '/payment-voucher/new',
    getParentRoute: () => ReceiptPaymentRoute,
  } as any)
const ReceiptPaymentPaymentVoucherIdRoute =
  ReceiptPaymentPaymentVoucherIdRouteImport.update({
    id: '/payment-voucher/$id',
    path: '/payment-voucher/$id',
    getParentRoute: () => ReceiptPaymentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ledgers': typeof LedgersRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/receipt-payment': typeof ReceiptPaymentRouteWithChildren
  '/vat-register': typeof VatRegisterRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/new': typeof BillsNewRoute
  '/challans/$id': typeof ChallansIdRoute
  '/challans/new': typeof ChallansNewRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/fixed-assets': typeof MastersFixedAssetsRoute
  '/masters/items': typeof MastersItemsRoute
  '/masters/vendors': typeof MastersVendorsRoute
  '/bills/': typeof BillsIndexRoute
  '/challans/': typeof ChallansIndexRoute
  '/receipt-payment/': typeof ReceiptPaymentIndexRoute
  '/receipt-payment/payment-voucher/$id': typeof ReceiptPaymentPaymentVoucherIdRoute
  '/receipt-payment/payment-voucher/new': typeof ReceiptPaymentPaymentVoucherNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ledgers': typeof LedgersRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/vat-register': typeof VatRegisterRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/new': typeof BillsNewRoute
  '/challans/$id': typeof ChallansIdRoute
  '/challans/new': typeof ChallansNewRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/fixed-assets': typeof MastersFixedAssetsRoute
  '/masters/items': typeof MastersItemsRoute
  '/masters/vendors': typeof MastersVendorsRoute
  '/bills': typeof BillsIndexRoute
  '/challans': typeof ChallansIndexRoute
  '/receipt-payment': typeof ReceiptPaymentIndexRoute
  '/receipt-payment/payment-voucher/$id': typeof ReceiptPaymentPaymentVoucherIdRoute
  '/receipt-payment/payment-voucher/new': typeof ReceiptPaymentPaymentVoucherNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ledgers': typeof LedgersRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/receipt-payment': typeof ReceiptPaymentRouteWithChildren
  '/vat-register': typeof VatRegisterRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/new': typeof BillsNewRoute
  '/challans/$id': typeof ChallansIdRoute
  '/challans/new': typeof ChallansNewRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/fixed-assets': typeof MastersFixedAssetsRoute
  '/masters/items': typeof MastersItemsRoute
  '/masters/vendors': typeof MastersVendorsRoute
  '/bills/': typeof BillsIndexRoute
  '/challans/': typeof ChallansIndexRoute
  '/receipt-payment/': typeof ReceiptPaymentIndexRoute
  '/receipt-payment/payment-voucher/$id': typeof ReceiptPaymentPaymentVoucherIdRoute
  '/receipt-payment/payment-voucher/new': typeof ReceiptPaymentPaymentVoucherNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ledgers'
    | '/login'
    | '/onboarding'
    | '/receipt-payment'
    | '/vat-register'
    | '/bills/$id'
    | '/bills/new'
    | '/challans/$id'
    | '/challans/new'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/fixed-assets'
    | '/masters/items'
    | '/masters/vendors'
    | '/bills/'
    | '/challans/'
    | '/receipt-payment/'
    | '/receipt-payment/payment-voucher/$id'
    | '/receipt-payment/payment-voucher/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ledgers'
    | '/login'
    | '/onboarding'
    | '/vat-register'
    | '/bills/$id'
    | '/bills/new'
    | '/challans/$id'
    | '/challans/new'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/fixed-assets'
    | '/masters/items'
    | '/masters/vendors'
    | '/bills'
    | '/challans'
    | '/receipt-payment'
    | '/receipt-payment/payment-voucher/$id'
    | '/receipt-payment/payment-voucher/new'
  id:
    | '__root__'
    | '/'
    | '/ledgers'
    | '/login'
    | '/onboarding'
    | '/receipt-payment'
    | '/vat-register'
    | '/bills/$id'
    | '/bills/new'
    | '/challans/$id'
    | '/challans/new'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/fixed-assets'
    | '/masters/items'
    | '/masters/vendors'
    | '/bills/'
    | '/challans/'
    | '/receipt-payment/'
    | '/receipt-payment/payment-voucher/$id'
    | '/receipt-payment/payment-voucher/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LedgersRoute: typeof LedgersRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ReceiptPaymentRoute: typeof ReceiptPaymentRouteWithChildren
  VatRegisterRoute: typeof VatRegisterRoute
  BillsIdRoute: typeof BillsIdRoute
  BillsNewRoute: typeof BillsNewRoute
  ChallansIdRoute: typeof ChallansIdRoute
  ChallansNewRoute: typeof ChallansNewRoute
  MastersCompaniesRoute: typeof MastersCompaniesRoute
  MastersCustomersRoute: typeof MastersCustomersRoute
  MastersFixedAssetsRoute: typeof MastersFixedAssetsRoute
  MastersItemsRoute: typeof MastersItemsRoute
  MastersVendorsRoute: typeof MastersVendorsRoute
  BillsIndexRoute: typeof BillsIndexRoute
  ChallansIndexRoute: typeof ChallansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vat-register': {
      id: '/vat-register'
      path: '/vat-register'
      fullPath: '/vat-register'
      preLoaderRoute: typeof VatRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-payment': {
      id: '/receipt-payment'
      path: '/receipt-payment'
      fullPath: '/receipt-payment'
      preLoaderRoute: typeof ReceiptPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledgers': {
      id: '/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof LedgersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-payment/': {
      id: '/receipt-payment/'
      path: '/'
      fullPath: '/receipt-payment/'
      preLoaderRoute: typeof ReceiptPaymentIndexRouteImport
      parentRoute: typeof ReceiptPaymentRoute
    }
    '/challans/': {
      id: '/challans/'
      path: '/challans'
      fullPath: '/challans/'
      preLoaderRoute: typeof ChallansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/vendors': {
      id: '/masters/vendors'
      path: '/masters/vendors'
      fullPath: '/masters/vendors'
      preLoaderRoute: typeof MastersVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/items': {
      id: '/masters/items'
      path: '/masters/items'
      fullPath: '/masters/items'
      preLoaderRoute: typeof MastersItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/fixed-assets': {
      id: '/masters/fixed-assets'
      path: '/masters/fixed-assets'
      fullPath: '/masters/fixed-assets'
      preLoaderRoute: typeof MastersFixedAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/customers': {
      id: '/masters/customers'
      path: '/masters/customers'
      fullPath: '/masters/customers'
      preLoaderRoute: typeof MastersCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/companies': {
      id: '/masters/companies'
      path: '/masters/companies'
      fullPath: '/masters/companies'
      preLoaderRoute: typeof MastersCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challans/new': {
      id: '/challans/new'
      path: '/challans/new'
      fullPath: '/challans/new'
      preLoaderRoute: typeof ChallansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challans/$id': {
      id: '/challans/$id'
      path: '/challans/$id'
      fullPath: '/challans/$id'
      preLoaderRoute: typeof ChallansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/new': {
      id: '/bills/new'
      path: '/bills/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof BillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-payment/payment-voucher/new': {
      id: '/receipt-payment/payment-voucher/new'
      path: '/payment-voucher/new'
      fullPath: '/receipt-payment/payment-voucher/new'
      preLoaderRoute: typeof ReceiptPaymentPaymentVoucherNewRouteImport
      parentRoute: typeof ReceiptPaymentRoute
    }
    '/receipt-payment/payment-voucher/$id': {
      id: '/receipt-payment/payment-voucher/$id'
      path: '/payment-voucher/$id'
      fullPath: '/receipt-payment/payment-voucher/$id'
      preLoaderRoute: typeof ReceiptPaymentPaymentVoucherIdRouteImport
      parentRoute: typeof ReceiptPaymentRoute
    }
  }
}

interface ReceiptPaymentRouteChildren {
  ReceiptPaymentIndexRoute: typeof ReceiptPaymentIndexRoute
  ReceiptPaymentPaymentVoucherIdRoute: typeof ReceiptPaymentPaymentVoucherIdRoute
  ReceiptPaymentPaymentVoucherNewRoute: typeof ReceiptPaymentPaymentVoucherNewRoute
}

const ReceiptPaymentRouteChildren: ReceiptPaymentRouteChildren = {
  ReceiptPaymentIndexRoute: ReceiptPaymentIndexRoute,
  ReceiptPaymentPaymentVoucherIdRoute: ReceiptPaymentPaymentVoucherIdRoute,
  ReceiptPaymentPaymentVoucherNewRoute: ReceiptPaymentPaymentVoucherNewRoute,
}

const ReceiptPaymentRouteWithChildren = ReceiptPaymentRoute._addFileChildren(
  ReceiptPaymentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LedgersRoute: LedgersRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ReceiptPaymentRoute: ReceiptPaymentRouteWithChildren,
  VatRegisterRoute: VatRegisterRoute,
  BillsIdRoute: BillsIdRoute,
  BillsNewRoute: BillsNewRoute,
  ChallansIdRoute: ChallansIdRoute,
  ChallansNewRoute: ChallansNewRoute,
  MastersCompaniesRoute: MastersCompaniesRoute,
  MastersCustomersRoute: MastersCustomersRoute,
  MastersFixedAssetsRoute: MastersFixedAssetsRoute,
  MastersItemsRoute: MastersItemsRoute,
  MastersVendorsRoute: MastersVendorsRoute,
  BillsIndexRoute: BillsIndexRoute,
  ChallansIndexRoute: ChallansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
