/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VatRegisterRouteImport } from './routes/vat-register'
import { Route as SalesReturnsRouteImport } from './routes/sales-returns'
import { Route as ReceiptPaymentRouteImport } from './routes/receipt-payment'
import { Route as PurchaseReturnsRouteImport } from './routes/purchase-returns'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LedgersRouteImport } from './routes/ledgers'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as JournalEntriesRouteImport } from './routes/journal-entries'
import { Route as GeneralLedgerRouteImport } from './routes/general-ledger'
import { Route as FixedAssetsRegisterRouteImport } from './routes/fixed-assets-register'
import { Route as CoaRouteImport } from './routes/coa'
import { Route as CashBankRouteImport } from './routes/cash-bank'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesReturnsIndexRouteImport } from './routes/sales-returns.index'
import { Route as SalesInvoicesIndexRouteImport } from './routes/sales-invoices.index'
import { Route as ReceiptPaymentIndexRouteImport } from './routes/receipt-payment.index'
import { Route as PurchaseReturnsIndexRouteImport } from './routes/purchase-returns.index'
import { Route as ConsumptionsIndexRouteImport } from './routes/consumptions.index'
import { Route as ChallansIndexRouteImport } from './routes/challans.index'
import { Route as CashBankIndexRouteImport } from './routes/cash-bank.index'
import { Route as BillsIndexRouteImport } from './routes/bills.index'
import { Route as SalesReturnsNewRouteImport } from './routes/sales-returns.new'
import { Route as SalesReturnsIdRouteImport } from './routes/sales-returns.$id'
import { Route as PurchaseReturnsNewRouteImport } from './routes/purchase-returns.new'
import { Route as PurchaseReturnsIdRouteImport } from './routes/purchase-returns.$id'
import { Route as MastersWarehousesRouteImport } from './routes/masters.warehouses'
import { Route as MastersVendorsRouteImport } from './routes/masters.vendors'
import { Route as MastersItemsRouteImport } from './routes/masters.items'
import { Route as MastersFixedAssetsRouteImport } from './routes/masters.fixed-assets'
import { Route as MastersCustomersRouteImport } from './routes/masters.customers'
import { Route as MastersCompaniesRouteImport } from './routes/masters.companies'
import { Route as ConsumptionsNewRouteImport } from './routes/consumptions.new'
import { Route as ConsumptionsIdRouteImport } from './routes/consumptions.$id'
import { Route as ChallansNewRouteImport } from './routes/challans.new'
import { Route as ChallansIdRouteImport } from './routes/challans.$id'
import { Route as BillsNewRouteImport } from './routes/bills.new'
import { Route as BillsIdRouteImport } from './routes/bills.$id'
import { Route as ReceiptPaymentReceiptVoucherNewRouteImport } from './routes/receipt-payment.receipt-voucher.new'
import { Route as ReceiptPaymentReceiptVoucherIdRouteImport } from './routes/receipt-payment.receipt-voucher.$id'
import { Route as ReceiptPaymentPaymentVoucherNewRouteImport } from './routes/receipt-payment.payment-voucher.new'
import { Route as ReceiptPaymentPaymentVoucherIdRouteImport } from './routes/receipt-payment.payment-voucher.$id'
import { Route as CashBankTransferNewRouteImport } from './routes/cash-bank.transfer.new'
import { Route as CashBankPettyCashNewRouteImport } from './routes/cash-bank.petty-cash.new'
import { Route as CashBankPettyCashIdRouteImport } from './routes/cash-bank.petty-cash.$id'
import { Route as CashBankLoanNewRouteImport } from './routes/cash-bank.loan.new'
import { Route as CashBankLoanIdRouteImport } from './routes/cash-bank.loan.$id'
import { Route as CashBankBankNewRouteImport } from './routes/cash-bank.bank.new'
import { Route as CashBankBankIdRouteImport } from './routes/cash-bank.bank.$id'
import { Route as CashBankPettyCashIdEditRouteImport } from './routes/cash-bank.petty-cash.$id.edit'
import { Route as CashBankLoanIdEditRouteImport } from './routes/cash-bank.loan.$id.edit'
import { Route as CashBankBankIdEditRouteImport } from './routes/cash-bank.bank.$id.edit'

const VatRegisterRoute = VatRegisterRouteImport.update({
  id: '/vat-register',
  path: '/vat-register',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReturnsRoute = SalesReturnsRouteImport.update({
  id: '/sales-returns',
  path: '/sales-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptPaymentRoute = ReceiptPaymentRouteImport.update({
  id: '/receipt-payment',
  path: '/receipt-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReturnsRoute = PurchaseReturnsRouteImport.update({
  id: '/purchase-returns',
  path: '/purchase-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgersRoute = LedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalEntriesRoute = JournalEntriesRouteImport.update({
  id: '/journal-entries',
  path: '/journal-entries',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneralLedgerRoute = GeneralLedgerRouteImport.update({
  id: '/general-ledger',
  path: '/general-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const FixedAssetsRegisterRoute = FixedAssetsRegisterRouteImport.update({
  id: '/fixed-assets-register',
  path: '/fixed-assets-register',
  getParentRoute: () => rootRouteImport,
} as any)
const CoaRoute = CoaRouteImport.update({
  id: '/coa',
  path: '/coa',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBankRoute = CashBankRouteImport.update({
  id: '/cash-bank',
  path: '/cash-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReturnsIndexRoute = SalesReturnsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesReturnsRoute,
} as any)
const SalesInvoicesIndexRoute = SalesInvoicesIndexRouteImport.update({
  id: '/sales-invoices/',
  path: '/sales-invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptPaymentIndexRoute = ReceiptPaymentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReceiptPaymentRoute,
} as any)
const PurchaseReturnsIndexRoute = PurchaseReturnsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchaseReturnsRoute,
} as any)
const ConsumptionsIndexRoute = ConsumptionsIndexRouteImport.update({
  id: '/consumptions/',
  path: '/consumptions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallansIndexRoute = ChallansIndexRouteImport.update({
  id: '/challans/',
  path: '/challans/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashBankIndexRoute = CashBankIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CashBankRoute,
} as any)
const BillsIndexRoute = BillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReturnsNewRoute = SalesReturnsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesReturnsRoute,
} as any)
const SalesReturnsIdRoute = SalesReturnsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SalesReturnsRoute,
} as any)
const PurchaseReturnsNewRoute = PurchaseReturnsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchaseReturnsRoute,
} as any)
const PurchaseReturnsIdRoute = PurchaseReturnsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PurchaseReturnsRoute,
} as any)
const MastersWarehousesRoute = MastersWarehousesRouteImport.update({
  id: '/masters/warehouses',
  path: '/masters/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersVendorsRoute = MastersVendorsRouteImport.update({
  id: '/masters/vendors',
  path: '/masters/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersItemsRoute = MastersItemsRouteImport.update({
  id: '/masters/items',
  path: '/masters/items',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersFixedAssetsRoute = MastersFixedAssetsRouteImport.update({
  id: '/masters/fixed-assets',
  path: '/masters/fixed-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCustomersRoute = MastersCustomersRouteImport.update({
  id: '/masters/customers',
  path: '/masters/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersCompaniesRoute = MastersCompaniesRouteImport.update({
  id: '/masters/companies',
  path: '/masters/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumptionsNewRoute = ConsumptionsNewRouteImport.update({
  id: '/consumptions/new',
  path: '/consumptions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumptionsIdRoute = ConsumptionsIdRouteImport.update({
  id: '/consumptions/$id',
  path: '/consumptions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallansNewRoute = ChallansNewRouteImport.update({
  id: '/challans/new',
  path: '/challans/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallansIdRoute = ChallansIdRouteImport.update({
  id: '/challans/$id',
  path: '/challans/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsNewRoute = BillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsIdRoute = BillsIdRouteImport.update({
  id: '/bills/$id',
  path: '/bills/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptPaymentReceiptVoucherNewRoute =
  ReceiptPaymentReceiptVoucherNewRouteImport.update({
    id: '/receipt-voucher/new',
    path: '/receipt-voucher/new',
    getParentRoute: () => ReceiptPaymentRoute,
  } as any)
const ReceiptPaymentReceiptVoucherIdRoute =
  ReceiptPaymentReceiptVoucherIdRouteImport.update({
    id: '/receipt-voucher/$id',
    path: '/receipt-voucher/$id',
    getParentRoute: () => ReceiptPaymentRoute,
  } as any)
const ReceiptPaymentPaymentVoucherNewRoute =
  ReceiptPaymentPaymentVoucherNewRouteImport.update({
    id: '/payment-voucher/new',
    path: '/payment-voucher/new',
    getParentRoute: () => ReceiptPaymentRoute,
  } as any)
const ReceiptPaymentPaymentVoucherIdRoute =
  ReceiptPaymentPaymentVoucherIdRouteImport.update({
    id: '/payment-voucher/$id',
    path: '/payment-voucher/$id',
    getParentRoute: () => ReceiptPaymentRoute,
  } as any)
const CashBankTransferNewRoute = CashBankTransferNewRouteImport.update({
  id: '/transfer/new',
  path: '/transfer/new',
  getParentRoute: () => CashBankRoute,
} as any)
const CashBankPettyCashNewRoute = CashBankPettyCashNewRouteImport.update({
  id: '/petty-cash/new',
  path: '/petty-cash/new',
  getParentRoute: () => CashBankRoute,
} as any)
const CashBankPettyCashIdRoute = CashBankPettyCashIdRouteImport.update({
  id: '/petty-cash/$id',
  path: '/petty-cash/$id',
  getParentRoute: () => CashBankRoute,
} as any)
const CashBankLoanNewRoute = CashBankLoanNewRouteImport.update({
  id: '/loan/new',
  path: '/loan/new',
  getParentRoute: () => CashBankRoute,
} as any)
const CashBankLoanIdRoute = CashBankLoanIdRouteImport.update({
  id: '/loan/$id',
  path: '/loan/$id',
  getParentRoute: () => CashBankRoute,
} as any)
const CashBankBankNewRoute = CashBankBankNewRouteImport.update({
  id: '/bank/new',
  path: '/bank/new',
  getParentRoute: () => CashBankRoute,
} as any)
const CashBankBankIdRoute = CashBankBankIdRouteImport.update({
  id: '/bank/$id',
  path: '/bank/$id',
  getParentRoute: () => CashBankRoute,
} as any)
const CashBankPettyCashIdEditRoute = CashBankPettyCashIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CashBankPettyCashIdRoute,
} as any)
const CashBankLoanIdEditRoute = CashBankLoanIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CashBankLoanIdRoute,
} as any)
const CashBankBankIdEditRoute = CashBankBankIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CashBankBankIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash-bank': typeof CashBankRouteWithChildren
  '/coa': typeof CoaRoute
  '/fixed-assets-register': typeof FixedAssetsRegisterRoute
  '/general-ledger': typeof GeneralLedgerRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/ledgers': typeof LedgersRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/purchase-returns': typeof PurchaseReturnsRouteWithChildren
  '/receipt-payment': typeof ReceiptPaymentRouteWithChildren
  '/sales-returns': typeof SalesReturnsRouteWithChildren
  '/vat-register': typeof VatRegisterRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/new': typeof BillsNewRoute
  '/challans/$id': typeof ChallansIdRoute
  '/challans/new': typeof ChallansNewRoute
  '/consumptions/$id': typeof ConsumptionsIdRoute
  '/consumptions/new': typeof ConsumptionsNewRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/fixed-assets': typeof MastersFixedAssetsRoute
  '/masters/items': typeof MastersItemsRoute
  '/masters/vendors': typeof MastersVendorsRoute
  '/masters/warehouses': typeof MastersWarehousesRoute
  '/purchase-returns/$id': typeof PurchaseReturnsIdRoute
  '/purchase-returns/new': typeof PurchaseReturnsNewRoute
  '/sales-returns/$id': typeof SalesReturnsIdRoute
  '/sales-returns/new': typeof SalesReturnsNewRoute
  '/bills/': typeof BillsIndexRoute
  '/cash-bank/': typeof CashBankIndexRoute
  '/challans/': typeof ChallansIndexRoute
  '/consumptions/': typeof ConsumptionsIndexRoute
  '/purchase-returns/': typeof PurchaseReturnsIndexRoute
  '/receipt-payment/': typeof ReceiptPaymentIndexRoute
  '/sales-invoices/': typeof SalesInvoicesIndexRoute
  '/sales-returns/': typeof SalesReturnsIndexRoute
  '/cash-bank/bank/$id': typeof CashBankBankIdRouteWithChildren
  '/cash-bank/bank/new': typeof CashBankBankNewRoute
  '/cash-bank/loan/$id': typeof CashBankLoanIdRouteWithChildren
  '/cash-bank/loan/new': typeof CashBankLoanNewRoute
  '/cash-bank/petty-cash/$id': typeof CashBankPettyCashIdRouteWithChildren
  '/cash-bank/petty-cash/new': typeof CashBankPettyCashNewRoute
  '/cash-bank/transfer/new': typeof CashBankTransferNewRoute
  '/receipt-payment/payment-voucher/$id': typeof ReceiptPaymentPaymentVoucherIdRoute
  '/receipt-payment/payment-voucher/new': typeof ReceiptPaymentPaymentVoucherNewRoute
  '/receipt-payment/receipt-voucher/$id': typeof ReceiptPaymentReceiptVoucherIdRoute
  '/receipt-payment/receipt-voucher/new': typeof ReceiptPaymentReceiptVoucherNewRoute
  '/cash-bank/bank/$id/edit': typeof CashBankBankIdEditRoute
  '/cash-bank/loan/$id/edit': typeof CashBankLoanIdEditRoute
  '/cash-bank/petty-cash/$id/edit': typeof CashBankPettyCashIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coa': typeof CoaRoute
  '/fixed-assets-register': typeof FixedAssetsRegisterRoute
  '/general-ledger': typeof GeneralLedgerRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/ledgers': typeof LedgersRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/vat-register': typeof VatRegisterRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/new': typeof BillsNewRoute
  '/challans/$id': typeof ChallansIdRoute
  '/challans/new': typeof ChallansNewRoute
  '/consumptions/$id': typeof ConsumptionsIdRoute
  '/consumptions/new': typeof ConsumptionsNewRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/fixed-assets': typeof MastersFixedAssetsRoute
  '/masters/items': typeof MastersItemsRoute
  '/masters/vendors': typeof MastersVendorsRoute
  '/masters/warehouses': typeof MastersWarehousesRoute
  '/purchase-returns/$id': typeof PurchaseReturnsIdRoute
  '/purchase-returns/new': typeof PurchaseReturnsNewRoute
  '/sales-returns/$id': typeof SalesReturnsIdRoute
  '/sales-returns/new': typeof SalesReturnsNewRoute
  '/bills': typeof BillsIndexRoute
  '/cash-bank': typeof CashBankIndexRoute
  '/challans': typeof ChallansIndexRoute
  '/consumptions': typeof ConsumptionsIndexRoute
  '/purchase-returns': typeof PurchaseReturnsIndexRoute
  '/receipt-payment': typeof ReceiptPaymentIndexRoute
  '/sales-invoices': typeof SalesInvoicesIndexRoute
  '/sales-returns': typeof SalesReturnsIndexRoute
  '/cash-bank/bank/$id': typeof CashBankBankIdRouteWithChildren
  '/cash-bank/bank/new': typeof CashBankBankNewRoute
  '/cash-bank/loan/$id': typeof CashBankLoanIdRouteWithChildren
  '/cash-bank/loan/new': typeof CashBankLoanNewRoute
  '/cash-bank/petty-cash/$id': typeof CashBankPettyCashIdRouteWithChildren
  '/cash-bank/petty-cash/new': typeof CashBankPettyCashNewRoute
  '/cash-bank/transfer/new': typeof CashBankTransferNewRoute
  '/receipt-payment/payment-voucher/$id': typeof ReceiptPaymentPaymentVoucherIdRoute
  '/receipt-payment/payment-voucher/new': typeof ReceiptPaymentPaymentVoucherNewRoute
  '/receipt-payment/receipt-voucher/$id': typeof ReceiptPaymentReceiptVoucherIdRoute
  '/receipt-payment/receipt-voucher/new': typeof ReceiptPaymentReceiptVoucherNewRoute
  '/cash-bank/bank/$id/edit': typeof CashBankBankIdEditRoute
  '/cash-bank/loan/$id/edit': typeof CashBankLoanIdEditRoute
  '/cash-bank/petty-cash/$id/edit': typeof CashBankPettyCashIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash-bank': typeof CashBankRouteWithChildren
  '/coa': typeof CoaRoute
  '/fixed-assets-register': typeof FixedAssetsRegisterRoute
  '/general-ledger': typeof GeneralLedgerRoute
  '/journal-entries': typeof JournalEntriesRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/ledgers': typeof LedgersRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/purchase-returns': typeof PurchaseReturnsRouteWithChildren
  '/receipt-payment': typeof ReceiptPaymentRouteWithChildren
  '/sales-returns': typeof SalesReturnsRouteWithChildren
  '/vat-register': typeof VatRegisterRoute
  '/bills/$id': typeof BillsIdRoute
  '/bills/new': typeof BillsNewRoute
  '/challans/$id': typeof ChallansIdRoute
  '/challans/new': typeof ChallansNewRoute
  '/consumptions/$id': typeof ConsumptionsIdRoute
  '/consumptions/new': typeof ConsumptionsNewRoute
  '/masters/companies': typeof MastersCompaniesRoute
  '/masters/customers': typeof MastersCustomersRoute
  '/masters/fixed-assets': typeof MastersFixedAssetsRoute
  '/masters/items': typeof MastersItemsRoute
  '/masters/vendors': typeof MastersVendorsRoute
  '/masters/warehouses': typeof MastersWarehousesRoute
  '/purchase-returns/$id': typeof PurchaseReturnsIdRoute
  '/purchase-returns/new': typeof PurchaseReturnsNewRoute
  '/sales-returns/$id': typeof SalesReturnsIdRoute
  '/sales-returns/new': typeof SalesReturnsNewRoute
  '/bills/': typeof BillsIndexRoute
  '/cash-bank/': typeof CashBankIndexRoute
  '/challans/': typeof ChallansIndexRoute
  '/consumptions/': typeof ConsumptionsIndexRoute
  '/purchase-returns/': typeof PurchaseReturnsIndexRoute
  '/receipt-payment/': typeof ReceiptPaymentIndexRoute
  '/sales-invoices/': typeof SalesInvoicesIndexRoute
  '/sales-returns/': typeof SalesReturnsIndexRoute
  '/cash-bank/bank/$id': typeof CashBankBankIdRouteWithChildren
  '/cash-bank/bank/new': typeof CashBankBankNewRoute
  '/cash-bank/loan/$id': typeof CashBankLoanIdRouteWithChildren
  '/cash-bank/loan/new': typeof CashBankLoanNewRoute
  '/cash-bank/petty-cash/$id': typeof CashBankPettyCashIdRouteWithChildren
  '/cash-bank/petty-cash/new': typeof CashBankPettyCashNewRoute
  '/cash-bank/transfer/new': typeof CashBankTransferNewRoute
  '/receipt-payment/payment-voucher/$id': typeof ReceiptPaymentPaymentVoucherIdRoute
  '/receipt-payment/payment-voucher/new': typeof ReceiptPaymentPaymentVoucherNewRoute
  '/receipt-payment/receipt-voucher/$id': typeof ReceiptPaymentReceiptVoucherIdRoute
  '/receipt-payment/receipt-voucher/new': typeof ReceiptPaymentReceiptVoucherNewRoute
  '/cash-bank/bank/$id/edit': typeof CashBankBankIdEditRoute
  '/cash-bank/loan/$id/edit': typeof CashBankLoanIdEditRoute
  '/cash-bank/petty-cash/$id/edit': typeof CashBankPettyCashIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash-bank'
    | '/coa'
    | '/fixed-assets-register'
    | '/general-ledger'
    | '/journal-entries'
    | '/knowledge-graph'
    | '/ledgers'
    | '/login'
    | '/onboarding'
    | '/purchase-returns'
    | '/receipt-payment'
    | '/sales-returns'
    | '/vat-register'
    | '/bills/$id'
    | '/bills/new'
    | '/challans/$id'
    | '/challans/new'
    | '/consumptions/$id'
    | '/consumptions/new'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/fixed-assets'
    | '/masters/items'
    | '/masters/vendors'
    | '/masters/warehouses'
    | '/purchase-returns/$id'
    | '/purchase-returns/new'
    | '/sales-returns/$id'
    | '/sales-returns/new'
    | '/bills/'
    | '/cash-bank/'
    | '/challans/'
    | '/consumptions/'
    | '/purchase-returns/'
    | '/receipt-payment/'
    | '/sales-invoices/'
    | '/sales-returns/'
    | '/cash-bank/bank/$id'
    | '/cash-bank/bank/new'
    | '/cash-bank/loan/$id'
    | '/cash-bank/loan/new'
    | '/cash-bank/petty-cash/$id'
    | '/cash-bank/petty-cash/new'
    | '/cash-bank/transfer/new'
    | '/receipt-payment/payment-voucher/$id'
    | '/receipt-payment/payment-voucher/new'
    | '/receipt-payment/receipt-voucher/$id'
    | '/receipt-payment/receipt-voucher/new'
    | '/cash-bank/bank/$id/edit'
    | '/cash-bank/loan/$id/edit'
    | '/cash-bank/petty-cash/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coa'
    | '/fixed-assets-register'
    | '/general-ledger'
    | '/journal-entries'
    | '/knowledge-graph'
    | '/ledgers'
    | '/login'
    | '/onboarding'
    | '/vat-register'
    | '/bills/$id'
    | '/bills/new'
    | '/challans/$id'
    | '/challans/new'
    | '/consumptions/$id'
    | '/consumptions/new'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/fixed-assets'
    | '/masters/items'
    | '/masters/vendors'
    | '/masters/warehouses'
    | '/purchase-returns/$id'
    | '/purchase-returns/new'
    | '/sales-returns/$id'
    | '/sales-returns/new'
    | '/bills'
    | '/cash-bank'
    | '/challans'
    | '/consumptions'
    | '/purchase-returns'
    | '/receipt-payment'
    | '/sales-invoices'
    | '/sales-returns'
    | '/cash-bank/bank/$id'
    | '/cash-bank/bank/new'
    | '/cash-bank/loan/$id'
    | '/cash-bank/loan/new'
    | '/cash-bank/petty-cash/$id'
    | '/cash-bank/petty-cash/new'
    | '/cash-bank/transfer/new'
    | '/receipt-payment/payment-voucher/$id'
    | '/receipt-payment/payment-voucher/new'
    | '/receipt-payment/receipt-voucher/$id'
    | '/receipt-payment/receipt-voucher/new'
    | '/cash-bank/bank/$id/edit'
    | '/cash-bank/loan/$id/edit'
    | '/cash-bank/petty-cash/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/cash-bank'
    | '/coa'
    | '/fixed-assets-register'
    | '/general-ledger'
    | '/journal-entries'
    | '/knowledge-graph'
    | '/ledgers'
    | '/login'
    | '/onboarding'
    | '/purchase-returns'
    | '/receipt-payment'
    | '/sales-returns'
    | '/vat-register'
    | '/bills/$id'
    | '/bills/new'
    | '/challans/$id'
    | '/challans/new'
    | '/consumptions/$id'
    | '/consumptions/new'
    | '/masters/companies'
    | '/masters/customers'
    | '/masters/fixed-assets'
    | '/masters/items'
    | '/masters/vendors'
    | '/masters/warehouses'
    | '/purchase-returns/$id'
    | '/purchase-returns/new'
    | '/sales-returns/$id'
    | '/sales-returns/new'
    | '/bills/'
    | '/cash-bank/'
    | '/challans/'
    | '/consumptions/'
    | '/purchase-returns/'
    | '/receipt-payment/'
    | '/sales-invoices/'
    | '/sales-returns/'
    | '/cash-bank/bank/$id'
    | '/cash-bank/bank/new'
    | '/cash-bank/loan/$id'
    | '/cash-bank/loan/new'
    | '/cash-bank/petty-cash/$id'
    | '/cash-bank/petty-cash/new'
    | '/cash-bank/transfer/new'
    | '/receipt-payment/payment-voucher/$id'
    | '/receipt-payment/payment-voucher/new'
    | '/receipt-payment/receipt-voucher/$id'
    | '/receipt-payment/receipt-voucher/new'
    | '/cash-bank/bank/$id/edit'
    | '/cash-bank/loan/$id/edit'
    | '/cash-bank/petty-cash/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashBankRoute: typeof CashBankRouteWithChildren
  CoaRoute: typeof CoaRoute
  FixedAssetsRegisterRoute: typeof FixedAssetsRegisterRoute
  GeneralLedgerRoute: typeof GeneralLedgerRoute
  JournalEntriesRoute: typeof JournalEntriesRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  LedgersRoute: typeof LedgersRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PurchaseReturnsRoute: typeof PurchaseReturnsRouteWithChildren
  ReceiptPaymentRoute: typeof ReceiptPaymentRouteWithChildren
  SalesReturnsRoute: typeof SalesReturnsRouteWithChildren
  VatRegisterRoute: typeof VatRegisterRoute
  BillsIdRoute: typeof BillsIdRoute
  BillsNewRoute: typeof BillsNewRoute
  ChallansIdRoute: typeof ChallansIdRoute
  ChallansNewRoute: typeof ChallansNewRoute
  ConsumptionsIdRoute: typeof ConsumptionsIdRoute
  ConsumptionsNewRoute: typeof ConsumptionsNewRoute
  MastersCompaniesRoute: typeof MastersCompaniesRoute
  MastersCustomersRoute: typeof MastersCustomersRoute
  MastersFixedAssetsRoute: typeof MastersFixedAssetsRoute
  MastersItemsRoute: typeof MastersItemsRoute
  MastersVendorsRoute: typeof MastersVendorsRoute
  MastersWarehousesRoute: typeof MastersWarehousesRoute
  BillsIndexRoute: typeof BillsIndexRoute
  ChallansIndexRoute: typeof ChallansIndexRoute
  ConsumptionsIndexRoute: typeof ConsumptionsIndexRoute
  SalesInvoicesIndexRoute: typeof SalesInvoicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vat-register': {
      id: '/vat-register'
      path: '/vat-register'
      fullPath: '/vat-register'
      preLoaderRoute: typeof VatRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-returns': {
      id: '/sales-returns'
      path: '/sales-returns'
      fullPath: '/sales-returns'
      preLoaderRoute: typeof SalesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-payment': {
      id: '/receipt-payment'
      path: '/receipt-payment'
      fullPath: '/receipt-payment'
      preLoaderRoute: typeof ReceiptPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-returns': {
      id: '/purchase-returns'
      path: '/purchase-returns'
      fullPath: '/purchase-returns'
      preLoaderRoute: typeof PurchaseReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledgers': {
      id: '/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof LedgersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal-entries': {
      id: '/journal-entries'
      path: '/journal-entries'
      fullPath: '/journal-entries'
      preLoaderRoute: typeof JournalEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/general-ledger': {
      id: '/general-ledger'
      path: '/general-ledger'
      fullPath: '/general-ledger'
      preLoaderRoute: typeof GeneralLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixed-assets-register': {
      id: '/fixed-assets-register'
      path: '/fixed-assets-register'
      fullPath: '/fixed-assets-register'
      preLoaderRoute: typeof FixedAssetsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coa': {
      id: '/coa'
      path: '/coa'
      fullPath: '/coa'
      preLoaderRoute: typeof CoaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-bank': {
      id: '/cash-bank'
      path: '/cash-bank'
      fullPath: '/cash-bank'
      preLoaderRoute: typeof CashBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-returns/': {
      id: '/sales-returns/'
      path: '/'
      fullPath: '/sales-returns/'
      preLoaderRoute: typeof SalesReturnsIndexRouteImport
      parentRoute: typeof SalesReturnsRoute
    }
    '/sales-invoices/': {
      id: '/sales-invoices/'
      path: '/sales-invoices'
      fullPath: '/sales-invoices/'
      preLoaderRoute: typeof SalesInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-payment/': {
      id: '/receipt-payment/'
      path: '/'
      fullPath: '/receipt-payment/'
      preLoaderRoute: typeof ReceiptPaymentIndexRouteImport
      parentRoute: typeof ReceiptPaymentRoute
    }
    '/purchase-returns/': {
      id: '/purchase-returns/'
      path: '/'
      fullPath: '/purchase-returns/'
      preLoaderRoute: typeof PurchaseReturnsIndexRouteImport
      parentRoute: typeof PurchaseReturnsRoute
    }
    '/consumptions/': {
      id: '/consumptions/'
      path: '/consumptions'
      fullPath: '/consumptions/'
      preLoaderRoute: typeof ConsumptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challans/': {
      id: '/challans/'
      path: '/challans'
      fullPath: '/challans/'
      preLoaderRoute: typeof ChallansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-bank/': {
      id: '/cash-bank/'
      path: '/'
      fullPath: '/cash-bank/'
      preLoaderRoute: typeof CashBankIndexRouteImport
      parentRoute: typeof CashBankRoute
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof BillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-returns/new': {
      id: '/sales-returns/new'
      path: '/new'
      fullPath: '/sales-returns/new'
      preLoaderRoute: typeof SalesReturnsNewRouteImport
      parentRoute: typeof SalesReturnsRoute
    }
    '/sales-returns/$id': {
      id: '/sales-returns/$id'
      path: '/$id'
      fullPath: '/sales-returns/$id'
      preLoaderRoute: typeof SalesReturnsIdRouteImport
      parentRoute: typeof SalesReturnsRoute
    }
    '/purchase-returns/new': {
      id: '/purchase-returns/new'
      path: '/new'
      fullPath: '/purchase-returns/new'
      preLoaderRoute: typeof PurchaseReturnsNewRouteImport
      parentRoute: typeof PurchaseReturnsRoute
    }
    '/purchase-returns/$id': {
      id: '/purchase-returns/$id'
      path: '/$id'
      fullPath: '/purchase-returns/$id'
      preLoaderRoute: typeof PurchaseReturnsIdRouteImport
      parentRoute: typeof PurchaseReturnsRoute
    }
    '/masters/warehouses': {
      id: '/masters/warehouses'
      path: '/masters/warehouses'
      fullPath: '/masters/warehouses'
      preLoaderRoute: typeof MastersWarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/vendors': {
      id: '/masters/vendors'
      path: '/masters/vendors'
      fullPath: '/masters/vendors'
      preLoaderRoute: typeof MastersVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/items': {
      id: '/masters/items'
      path: '/masters/items'
      fullPath: '/masters/items'
      preLoaderRoute: typeof MastersItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/fixed-assets': {
      id: '/masters/fixed-assets'
      path: '/masters/fixed-assets'
      fullPath: '/masters/fixed-assets'
      preLoaderRoute: typeof MastersFixedAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/customers': {
      id: '/masters/customers'
      path: '/masters/customers'
      fullPath: '/masters/customers'
      preLoaderRoute: typeof MastersCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters/companies': {
      id: '/masters/companies'
      path: '/masters/companies'
      fullPath: '/masters/companies'
      preLoaderRoute: typeof MastersCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumptions/new': {
      id: '/consumptions/new'
      path: '/consumptions/new'
      fullPath: '/consumptions/new'
      preLoaderRoute: typeof ConsumptionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumptions/$id': {
      id: '/consumptions/$id'
      path: '/consumptions/$id'
      fullPath: '/consumptions/$id'
      preLoaderRoute: typeof ConsumptionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challans/new': {
      id: '/challans/new'
      path: '/challans/new'
      fullPath: '/challans/new'
      preLoaderRoute: typeof ChallansNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challans/$id': {
      id: '/challans/$id'
      path: '/challans/$id'
      fullPath: '/challans/$id'
      preLoaderRoute: typeof ChallansIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/new': {
      id: '/bills/new'
      path: '/bills/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof BillsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills/$id': {
      id: '/bills/$id'
      path: '/bills/$id'
      fullPath: '/bills/$id'
      preLoaderRoute: typeof BillsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt-payment/receipt-voucher/new': {
      id: '/receipt-payment/receipt-voucher/new'
      path: '/receipt-voucher/new'
      fullPath: '/receipt-payment/receipt-voucher/new'
      preLoaderRoute: typeof ReceiptPaymentReceiptVoucherNewRouteImport
      parentRoute: typeof ReceiptPaymentRoute
    }
    '/receipt-payment/receipt-voucher/$id': {
      id: '/receipt-payment/receipt-voucher/$id'
      path: '/receipt-voucher/$id'
      fullPath: '/receipt-payment/receipt-voucher/$id'
      preLoaderRoute: typeof ReceiptPaymentReceiptVoucherIdRouteImport
      parentRoute: typeof ReceiptPaymentRoute
    }
    '/receipt-payment/payment-voucher/new': {
      id: '/receipt-payment/payment-voucher/new'
      path: '/payment-voucher/new'
      fullPath: '/receipt-payment/payment-voucher/new'
      preLoaderRoute: typeof ReceiptPaymentPaymentVoucherNewRouteImport
      parentRoute: typeof ReceiptPaymentRoute
    }
    '/receipt-payment/payment-voucher/$id': {
      id: '/receipt-payment/payment-voucher/$id'
      path: '/payment-voucher/$id'
      fullPath: '/receipt-payment/payment-voucher/$id'
      preLoaderRoute: typeof ReceiptPaymentPaymentVoucherIdRouteImport
      parentRoute: typeof ReceiptPaymentRoute
    }
    '/cash-bank/transfer/new': {
      id: '/cash-bank/transfer/new'
      path: '/transfer/new'
      fullPath: '/cash-bank/transfer/new'
      preLoaderRoute: typeof CashBankTransferNewRouteImport
      parentRoute: typeof CashBankRoute
    }
    '/cash-bank/petty-cash/new': {
      id: '/cash-bank/petty-cash/new'
      path: '/petty-cash/new'
      fullPath: '/cash-bank/petty-cash/new'
      preLoaderRoute: typeof CashBankPettyCashNewRouteImport
      parentRoute: typeof CashBankRoute
    }
    '/cash-bank/petty-cash/$id': {
      id: '/cash-bank/petty-cash/$id'
      path: '/petty-cash/$id'
      fullPath: '/cash-bank/petty-cash/$id'
      preLoaderRoute: typeof CashBankPettyCashIdRouteImport
      parentRoute: typeof CashBankRoute
    }
    '/cash-bank/loan/new': {
      id: '/cash-bank/loan/new'
      path: '/loan/new'
      fullPath: '/cash-bank/loan/new'
      preLoaderRoute: typeof CashBankLoanNewRouteImport
      parentRoute: typeof CashBankRoute
    }
    '/cash-bank/loan/$id': {
      id: '/cash-bank/loan/$id'
      path: '/loan/$id'
      fullPath: '/cash-bank/loan/$id'
      preLoaderRoute: typeof CashBankLoanIdRouteImport
      parentRoute: typeof CashBankRoute
    }
    '/cash-bank/bank/new': {
      id: '/cash-bank/bank/new'
      path: '/bank/new'
      fullPath: '/cash-bank/bank/new'
      preLoaderRoute: typeof CashBankBankNewRouteImport
      parentRoute: typeof CashBankRoute
    }
    '/cash-bank/bank/$id': {
      id: '/cash-bank/bank/$id'
      path: '/bank/$id'
      fullPath: '/cash-bank/bank/$id'
      preLoaderRoute: typeof CashBankBankIdRouteImport
      parentRoute: typeof CashBankRoute
    }
    '/cash-bank/petty-cash/$id/edit': {
      id: '/cash-bank/petty-cash/$id/edit'
      path: '/edit'
      fullPath: '/cash-bank/petty-cash/$id/edit'
      preLoaderRoute: typeof CashBankPettyCashIdEditRouteImport
      parentRoute: typeof CashBankPettyCashIdRoute
    }
    '/cash-bank/loan/$id/edit': {
      id: '/cash-bank/loan/$id/edit'
      path: '/edit'
      fullPath: '/cash-bank/loan/$id/edit'
      preLoaderRoute: typeof CashBankLoanIdEditRouteImport
      parentRoute: typeof CashBankLoanIdRoute
    }
    '/cash-bank/bank/$id/edit': {
      id: '/cash-bank/bank/$id/edit'
      path: '/edit'
      fullPath: '/cash-bank/bank/$id/edit'
      preLoaderRoute: typeof CashBankBankIdEditRouteImport
      parentRoute: typeof CashBankBankIdRoute
    }
  }
}

interface CashBankBankIdRouteChildren {
  CashBankBankIdEditRoute: typeof CashBankBankIdEditRoute
}

const CashBankBankIdRouteChildren: CashBankBankIdRouteChildren = {
  CashBankBankIdEditRoute: CashBankBankIdEditRoute,
}

const CashBankBankIdRouteWithChildren = CashBankBankIdRoute._addFileChildren(
  CashBankBankIdRouteChildren,
)

interface CashBankLoanIdRouteChildren {
  CashBankLoanIdEditRoute: typeof CashBankLoanIdEditRoute
}

const CashBankLoanIdRouteChildren: CashBankLoanIdRouteChildren = {
  CashBankLoanIdEditRoute: CashBankLoanIdEditRoute,
}

const CashBankLoanIdRouteWithChildren = CashBankLoanIdRoute._addFileChildren(
  CashBankLoanIdRouteChildren,
)

interface CashBankPettyCashIdRouteChildren {
  CashBankPettyCashIdEditRoute: typeof CashBankPettyCashIdEditRoute
}

const CashBankPettyCashIdRouteChildren: CashBankPettyCashIdRouteChildren = {
  CashBankPettyCashIdEditRoute: CashBankPettyCashIdEditRoute,
}

const CashBankPettyCashIdRouteWithChildren =
  CashBankPettyCashIdRoute._addFileChildren(CashBankPettyCashIdRouteChildren)

interface CashBankRouteChildren {
  CashBankIndexRoute: typeof CashBankIndexRoute
  CashBankBankIdRoute: typeof CashBankBankIdRouteWithChildren
  CashBankBankNewRoute: typeof CashBankBankNewRoute
  CashBankLoanIdRoute: typeof CashBankLoanIdRouteWithChildren
  CashBankLoanNewRoute: typeof CashBankLoanNewRoute
  CashBankPettyCashIdRoute: typeof CashBankPettyCashIdRouteWithChildren
  CashBankPettyCashNewRoute: typeof CashBankPettyCashNewRoute
  CashBankTransferNewRoute: typeof CashBankTransferNewRoute
}

const CashBankRouteChildren: CashBankRouteChildren = {
  CashBankIndexRoute: CashBankIndexRoute,
  CashBankBankIdRoute: CashBankBankIdRouteWithChildren,
  CashBankBankNewRoute: CashBankBankNewRoute,
  CashBankLoanIdRoute: CashBankLoanIdRouteWithChildren,
  CashBankLoanNewRoute: CashBankLoanNewRoute,
  CashBankPettyCashIdRoute: CashBankPettyCashIdRouteWithChildren,
  CashBankPettyCashNewRoute: CashBankPettyCashNewRoute,
  CashBankTransferNewRoute: CashBankTransferNewRoute,
}

const CashBankRouteWithChildren = CashBankRoute._addFileChildren(
  CashBankRouteChildren,
)

interface PurchaseReturnsRouteChildren {
  PurchaseReturnsIdRoute: typeof PurchaseReturnsIdRoute
  PurchaseReturnsNewRoute: typeof PurchaseReturnsNewRoute
  PurchaseReturnsIndexRoute: typeof PurchaseReturnsIndexRoute
}

const PurchaseReturnsRouteChildren: PurchaseReturnsRouteChildren = {
  PurchaseReturnsIdRoute: PurchaseReturnsIdRoute,
  PurchaseReturnsNewRoute: PurchaseReturnsNewRoute,
  PurchaseReturnsIndexRoute: PurchaseReturnsIndexRoute,
}

const PurchaseReturnsRouteWithChildren = PurchaseReturnsRoute._addFileChildren(
  PurchaseReturnsRouteChildren,
)

interface ReceiptPaymentRouteChildren {
  ReceiptPaymentIndexRoute: typeof ReceiptPaymentIndexRoute
  ReceiptPaymentPaymentVoucherIdRoute: typeof ReceiptPaymentPaymentVoucherIdRoute
  ReceiptPaymentPaymentVoucherNewRoute: typeof ReceiptPaymentPaymentVoucherNewRoute
  ReceiptPaymentReceiptVoucherIdRoute: typeof ReceiptPaymentReceiptVoucherIdRoute
  ReceiptPaymentReceiptVoucherNewRoute: typeof ReceiptPaymentReceiptVoucherNewRoute
}

const ReceiptPaymentRouteChildren: ReceiptPaymentRouteChildren = {
  ReceiptPaymentIndexRoute: ReceiptPaymentIndexRoute,
  ReceiptPaymentPaymentVoucherIdRoute: ReceiptPaymentPaymentVoucherIdRoute,
  ReceiptPaymentPaymentVoucherNewRoute: ReceiptPaymentPaymentVoucherNewRoute,
  ReceiptPaymentReceiptVoucherIdRoute: ReceiptPaymentReceiptVoucherIdRoute,
  ReceiptPaymentReceiptVoucherNewRoute: ReceiptPaymentReceiptVoucherNewRoute,
}

const ReceiptPaymentRouteWithChildren = ReceiptPaymentRoute._addFileChildren(
  ReceiptPaymentRouteChildren,
)

interface SalesReturnsRouteChildren {
  SalesReturnsIdRoute: typeof SalesReturnsIdRoute
  SalesReturnsNewRoute: typeof SalesReturnsNewRoute
  SalesReturnsIndexRoute: typeof SalesReturnsIndexRoute
}

const SalesReturnsRouteChildren: SalesReturnsRouteChildren = {
  SalesReturnsIdRoute: SalesReturnsIdRoute,
  SalesReturnsNewRoute: SalesReturnsNewRoute,
  SalesReturnsIndexRoute: SalesReturnsIndexRoute,
}

const SalesReturnsRouteWithChildren = SalesReturnsRoute._addFileChildren(
  SalesReturnsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashBankRoute: CashBankRouteWithChildren,
  CoaRoute: CoaRoute,
  FixedAssetsRegisterRoute: FixedAssetsRegisterRoute,
  GeneralLedgerRoute: GeneralLedgerRoute,
  JournalEntriesRoute: JournalEntriesRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  LedgersRoute: LedgersRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PurchaseReturnsRoute: PurchaseReturnsRouteWithChildren,
  ReceiptPaymentRoute: ReceiptPaymentRouteWithChildren,
  SalesReturnsRoute: SalesReturnsRouteWithChildren,
  VatRegisterRoute: VatRegisterRoute,
  BillsIdRoute: BillsIdRoute,
  BillsNewRoute: BillsNewRoute,
  ChallansIdRoute: ChallansIdRoute,
  ChallansNewRoute: ChallansNewRoute,
  ConsumptionsIdRoute: ConsumptionsIdRoute,
  ConsumptionsNewRoute: ConsumptionsNewRoute,
  MastersCompaniesRoute: MastersCompaniesRoute,
  MastersCustomersRoute: MastersCustomersRoute,
  MastersFixedAssetsRoute: MastersFixedAssetsRoute,
  MastersItemsRoute: MastersItemsRoute,
  MastersVendorsRoute: MastersVendorsRoute,
  MastersWarehousesRoute: MastersWarehousesRoute,
  BillsIndexRoute: BillsIndexRoute,
  ChallansIndexRoute: ChallansIndexRoute,
  ConsumptionsIndexRoute: ConsumptionsIndexRoute,
  SalesInvoicesIndexRoute: SalesInvoicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
